image: ubuntu:bionic
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake qt5-default g++ libreadline-dev build-essential
build:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j2
